=== Zubychi/PB029/druhy_zapoctovy_dokument/contacts.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="contacts">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="record" type="record-type"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="record-type">
        <xs:sequence>
            <xs:element name="name" type="name-type"/>        
            <xs:element name="address" type="address-type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="phone" type="phone-type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="email" type="email-type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="web" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="personalized-contact" type="personalized-contact-type" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="name-type">
        <xs:sequence>
            <xs:element name="lastname" type="xs:string"/>
            <xs:element name="firstname" type="xs:string"/>
            <xs:element name="middlename" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="address-type">
        <xs:sequence>
            <xs:element name="street" type="xs:string"/>
            <xs:element name="house-number" type="xs:string"/>
            <xs:element name="zipcode" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="contact-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="personal"/>
            <xs:enumeration value="work"/>
            <xs:enumeration value="academic"/>
            <xs:enumeration value="other"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="phone-type">
        <xs:sequence>
            <xs:element name="type" type="contact-type"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="email-type">
        <xs:sequence>
            <xs:element name="type" type="contact-type"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="personalized-contact-type">
        <xs:sequence>
            <xs:element name="service" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Zubychi/PB029/druhy_zapoctovy_dokument/valid_examples/example3.xml
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../contacts.xsd">

    <record>
        <name>
            <lastname>Rudincová</lastname>
            <firstname>Denisa</firstname>
            <middlename>Cecília</middlename>
        </name>

        <address>
            <street>Fialková</street>
            <house-number>42</house-number>
            <zipcode>424242</zipcode>
            <city>Lentilkovo</city>
            <country>Slovensko</country>
        </address>

        <phone>
            <type>personal</type>
            <value>+424242424242</value>
        </phone>

        <email>
            <type>academic</type>
            <value>524996@mail.muni.cz</value>
        </email>

        <email>
            <type>work</type>
            <value>xrudinc@fi.muni.cz</value>
        </email>
    
        <email>
            <type>personal</type>
            <value>denisa.rudinec@gmail.com</value>
        </email>

        <web>https://idkkflmln.sk</web>

        <personalized-contact>
            <service>Discord</service>
            <value>addsadsakjdsakjkja</value>
        </personalized-contact>

        <note>Poznámka č. 1</note>
        <note>Poznámka č. 2</note>
        <note>Not an empty note</note>
        <note>After the Battle of New York, the world has changed. It now knows not only about the Avengers, but also the powerful menaces that require those superheroes and more to face them. In response, Phil Coulson of the Strategic Homeland Intervention, Enforcement and Logistics Division assembles an elite covert team to find and deal with these threats wherever they are found. With a world rapidly becoming more bizarre and dangerous than ever before as the supervillains arise, these agents of S.H.I.E.L.D. are ready to take them on.</note>
    </record>

    <record>
        <name>
            <lastname>Veronesi</lastname>
            <firstname>Mia</firstname>
            <middlename>Rin</middlename>
        </name>
    </record>

    <record>
        <name>
            <lastname>Johnson</lastname>
            <firstname>Daisy</firstname>
        </name>

        <address>
            <street>Some village</street>
            <house-number>1</house-number>
            <zipcode>22222222</zipcode>
            <city>Some village</city>
            <country>China</country>
        </address>

        <personalized-contact>
            <service>Facebook</service>
            <value>Daisy Quake Johnson</value>
        </personalized-contact>

        <note>Also known as Quake, which I totally didn't read as Quack the first time I saw it.</note>
    </record>

    <record>
        <name>
            <lastname>Zabo</lastname>
            <firstname>Calvin</firstname>
        </name>

        <address>
            <street>Some village</street>
            <house-number>1</house-number>
            <zipcode>22222222</zipcode>
            <city>Some village</city>
            <country>China</country>
        </address>

        <email>
            <type>work</type>
            <value>winslow@vetclinic.com</value>
        </email>
    

        <note>Quack's biological father.</note>
        <note>My fav character, btw.</note>
    </record>

    <record>
        <name>
            <lastname>Johnson</lastname>
            <firstname>Jiaying</firstname>
        </name>

        <address>
            <street>Some village</street>
            <house-number>1</house-number>
            <zipcode>22222222</zipcode>
            <city>Some village</city>
            <country>China</country>
        </address>

        <address>
            <street>Afterlife</street>
            <house-number>0</house-number>
            <zipcode>Unknown</zipcode>
            <city>Afterlife</city>
            <country>Unknown</country>
        </address>

        <personalized-contact>
            <service>Discord</service>
            <value>Jiyang42335</value>
        </personalized-contact>

        <note>Quack's mom.</note>
    </record>

</contacts>

=== Zubychi/PB029/druhy_zapoctovy_dokument/valid_examples/example2.xml
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../contacts.xsd">

    <record>
        <name>
            <lastname>Rudincová</lastname>
            <firstname>Denisa</firstname>
            <middlename>Cecília</middlename>
        </name>

        <address>
            <street>Fialková</street>
            <house-number>42</house-number>
            <zipcode>424242</zipcode>
            <city>Lentilkovo</city>
            <country>Slovensko</country>
        </address>

        <phone>
            <type>personal</type>
            <value>+424242424242</value>
        </phone>

        <email>
            <type>academic</type>
            <value>524996@mail.muni.cz</value>
        </email>

        <email>
            <type>work</type>
            <value>xrudinc@fi.muni.cz</value>
        </email>
    
        <email>
            <type>personal</type>
            <value>denisa.rudinec@gmail.com</value>
        </email>

        <web>https://idkkflmln.sk</web>

        <personalized-contact>
            <service>Discord</service>
            <value>-</value>
        </personalized-contact>

        <note>Poznámka č. 1</note>
        <note>Poznámka č. 2</note>
        <note>Poznámka č. 3</note>
    </record>

</contacts>
